### ISSUE TITLE
File format for animation/skeleton

### ISSUE THREAD

**Issue by NinjaDanz3r** [Chainsawkitten/LargeGameProjectEngine#146]
Create a format that lets animation component take skeleton as a resource instead of having a skeleton component.
-------------------------------------
Original:
Add skeleton component in order to handle meshes with skeletons.

**Comment by ludvigarlebrink** [comment]
Maybe not skeleton as a component but as a resource type. I think just an "Animation" or "Animator" component that takes, skeleton and an array of animations as input, would be enough. So that the entity won't be overcrowded with components, and to avoid component dependencies.

**Comment by andens** [comment]
Updated the existing task for the current sprint to represent what the task is supposed to do.
