### ISSUE TITLE
Crash when opening Scene 0

### ISSUE THREAD

**Issue by Sajdkick** [Chainsawkitten/LargeGameProjectEngine#157]
Create a new hymn.
Open Scene 0.
Ctrl + S.
Instantiate Scene 0 in Scene 0.
Try to load it.
Crash.
Open HTB again.
Create a new hymn with the same name as the earlier one.
Open Scene 0.
Crash.

This works for any scene that had the same name in an earlier hymn with the same name that crashed.

**Comment by NinjaDanz3r** [comment]
Tested and unable to reproduce, closing issue.
