### ISSUE TITLE
Research how to organize multiple cameras

### ISSUE THREAD

**Issue by andens** [Chainsawkitten/LargeGameProjectEngine#195]
Entities are restricted to a single component of each type. This implies that we cannot have two cameras on an entity. Early suggestions were to let the camera be of a VR kind or make two entities, each with their own camera.

**Comment by LarsIngo** [comment]
At construction of RenderManger, pass parameter if we are using VR. If we're using VR, create an additional RenderSurface and render to it as well. Render each eye separately to lower memory usage.
