### ISSUE TITLE
Hide entities constructor

### ISSUE THREAD

**Issue by NinjaDanz3r** [Chainsawkitten/LargeGameProjectEngine#236]
Currently Entity's constructor is public, which makes it possible to create entities outside World.
Thus, instantiating an entity without giving it a pointer to an active world will cause crashes when trying to add components to the entity.

This can be fixed by hiding the constructor and making it a friend class to World.

**Comment by andens** [comment]
This also ails components to some degree. It would be nice with hidden component constructors to force creation through managers, thus ensuring that components are created in a valid state.
