### ISSUE TITLE
Able to add not imported mesh as mesh component.

### ISSUE THREAD

**Issue by ludvigarlebrink** [Chainsawkitten/LargeGameProjectEngine#321]
Steps to reproduce:
1. Create a model, without importing a fbx file
2. Create a mesh component on a entity
3. You will now be able to add the not imported mesh to the component.

**Comment by LarsIngo** [comment]
Fixed by setting a default model to model resource?

**Comment by Ittis** [comment]
Still not wokring. will be moved to "wontfix"
