### ISSUE TITLE
Unable to select scene in editor.

### ISSUE THREAD

**Issue by andens** [Chainsawkitten/LargeGameProjectEngine#380]
Clicking a scene in the resource list no longer opens the left-side bar to edit it. This bug was likely introduced in https://github.com/Chainsawkitten/LargeGameProjectEngine/commit/fec711b20ff5e07793b42833de73e45abd658dbc or https://github.com/Chainsawkitten/LargeGameProjectEngine/commit/14853aaa59361de4fdca5ebb9e03e139dc7b807d.

**Comment by Chainsawkitten** [comment]
Can't reproduce. Fixed?

**Comment by andens** [comment]
Closing as the bug no longer applies.
