### ISSUE TITLE
Cannot click point light in scene

### ISSUE THREAD

**Issue by andens** [Chainsawkitten/LargeGameProjectEngine#413]
In the editor as of https://github.com/Chainsawkitten/LargeGameProjectEngine/commit/802590e813593bd520337bcb5d8243620683d377 the cave is selected instead of the point light when clicking it.

Reproduce:
- Start editor
- Load game
- Click point light in the middle of the screen
- Cave is selected instead of light

**Comment by SwedishSock** [comment]
Working as intended, you are only supposed to be able to click on meshes.
