### ISSUE TITLE
Scaling the mesh does not scale the bounding box.

### ISSUE THREAD

**Issue by marredal** [Chainsawkitten/LargeGameProjectEngine#454]
Scaling the mesh does not scale the bounding box and leads to mousepicking being unreliable in the editor.
How to reproduce:
Scale mesh by 5 (for example).
Try to select mesh.

**Comment by LarsIngo** [comment]
Could bullet be used to get accurate picking by using ray vs box/mesh? If bullet is used, scale problem will also be fixed.
