### ISSUE TITLE
Crash when dereferencing invalid string

### ISSUE THREAD

**Issue by andens** [Chainsawkitten/LargeGameProjectEngine#484]
Reproduce:
- Open the game project
- Open resources
- Add a scene by right-clicking resources
- Select the added scene
- Add a model by right-clicking resources
- Crash in `SceneEditor::Show`, it seems that `scene` is a dangling pointer.

**Comment by Chainsawkitten** [comment]
Probable cause: resources are stored in a vector in ResourceFolder in ResourceList. When adding a scene, the vector is resized and so the resource's scene string is no longer valid.
