### ISSUE TITLE
Point light : View frustum culling

### ISSUE THREAD

**Issue by LarsIngo** [Chainsawkitten/LargeGameProjectEngine#603]
Remove ambient from point light as they are view frustum culled.

**Comment by andens** [comment]
Is this bug solved with [using 0 ambient for point lights](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/master/src/Engine/Manager/RenderManager.cpp#L752)?

**Comment by andens** [comment]
Closing in consultation with @LarsIngo; this is no longer a bug.
