### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by NinjaDanz3r** [Chainsawkitten/LargeGameProjectEngine#642]
Open game
Turn around 180 degrees
You will notice that the lighting drastically changes, see following screenshots:
![startposition](https://user-images.githubusercontent.com/10200316/31819993-70a7974e-b59f-11e7-9434-870b3368fadc.png)
![endposition](https://user-images.githubusercontent.com/10200316/31819996-73120834-b59f-11e7-9e84-977f13bdf1b3.png)

**Comment by LarsIngo** [comment]
That is because the point light has an ambient light attribute and the point light is culled when looking away from it.

**Comment by LarsIngo** [comment]
Fix: Remove ambient attribute
