### ISSUE TITLE
Light Source emitting Blue light

### ISSUE THREAD

**Issue by abdominator** [Chainsawkitten/LargeGameProjectEngine#647]
In a project with multiple textures and models, only one light source could be created correctly. When adding more than one light the global lighting of the scene becomes blue and looks like a directional light.

Issue appeared with project of following settings:
- 5 models
- 20 textures (4 for each model)
- Adding a point light. (This light works as expected).
**- Adding another light source of optional type. (Light now becomes blue)**

Changing the color of the first point light then affects the color of the blue tone.

**Comment by LarsIngo** [comment]
Light storage buffer has to be padded.

**Comment by LarsIngo** [comment]
Solved?
