### ISSUE TITLE
Determine whether we should bake metallic and roughness

### ISSUE THREAD

**Issue by Chainsawkitten** [Chainsawkitten/LargeGameProjectEngine#856]
Baking metallic and roughness into the alpha channels of albedo and normal would reduce the number of texture samples and texture bindings we do. We need to determine whether this helps improve the framerate and is worth pursuing or whether we should stick to 4 separate textures.

**Comment by Ittis** [comment]
Preformance diff:
1080fullscreen:  20.7484 ms - 19.5722 ms
720fullscreen: 12.2204 ms - 11.0444 ms
No need to bake alpha
