### ISSUE TITLE
Make bucket more noticeable

### ISSUE THREAD

**Issue by NinjaDanz3r** [Chainsawkitten/LargeGameProjectEngine#859]
Some users did not see the bucket initially without prompting.
Making it more distinguishable againt the background would be a good idea.

**Comment by Chainsawkitten** [comment]
Suggestion: Make it wooden.

**Comment by andens** [comment]
Suggestion: Make the bucket have some text or other imprint in sharp colors, e.g. something sprayed in orange color.

**Comment by andens** [comment]
Suggestion: Use a light to draw attention.
