### ISSUE TITLE
Show the player the controls on startup

### ISSUE THREAD

**Issue by NinjaDanz3r** [Chainsawkitten/LargeGameProjectEngine#860]
Some users did not know which controls to use.
When starting the game there should be some form of tutorial or information on which controls to use.

**Comment by andens** [comment]
I think this will mostly be solved by being immobile at the start of the game, waiting for the player to pull a (quite frankly obvious) lever. Being immobile allows the player to experiment until she understands how to interact with objects. To make the lever very obvious, as a special case we could render this particular object pulsating to indicate that it's interactable without actually saying so in text.
